import { readFileSync, renameSync, writeFileSync } from "node:fs";

const ENV_PATH = ".env";
const LineEnding = /\r?\n/;

export function buildFixtureValues(): Record<string, string> {
	return {
		FIXTURE_API_KEY: `sk-proj-${"AbCdEfGhIjKlMnOpQrStUvWxYz0123456789"}`,
		FIXTURE_AWS_KEY: `AKIA${"IOSFODNN7EXAMPLE"}`,
		FIXTURE_BEARER_TOKEN: `Bearer ${"abcdefghijklmnopqrstuvwxyz012345"}`,
		FIXTURE_GITHUB_TOKEN: `ghp_${"abcdefghijklmnopqrstuvwxyz0123456789abcd"}`,
		FIXTURE_JWT: `eyJhbGciOiJIUzI1NiJ9.${"eyJzdWIiOiIxIn0"}.abcde`,
		FIXTURE_PRIVATE_KEY_HEADER: `-----BEGIN ${"PRIVATE KEY-----"}`,
		FIXTURE_SLACK_TOKEN: `xoxb-${"123456789012-123456789012-abcdefghijklmnopqrstuvwx"}`,
	};
}

export function renderFixtureEnv(values: Record<string, string>): string {
	const lines = [
		"# Generated by bun run fixtures:env — fake detector fixtures, never commit this file.",
		...Object.entries(values).map(([key, value]) => `${key}=${value}`),
	];
	return `${lines.join("\n")}\n`;
}

export function ensureFixtureEnv(path: string = ENV_PATH): void {
	let existing = "";
	try {
		existing = readFileSync(path, "utf8");
	} catch {
		existing = "";
	}
	const values = buildFixtureValues();
	const lines = existing.split(LineEnding).filter((line) => line.trim().length > 0);
	let missing = false;
	for (const [key, value] of Object.entries(values)) {
		if (!lines.some((line) => line.startsWith(`${key}=`))) {
			lines.push(`${key}=${value}`);
			missing = true;
		}
	}
	if (missing) {
		const tempPath = `${path}.tmp-${process.pid}`;
		writeFileSync(tempPath, `${lines.join("\n")}\n`);
		renameSync(tempPath, path);
	}
}

ensureFixtureEnv();
