/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ApiDecisionsRouteImport } from './routes/api.decisions'
import { Route as ApiGuardRouteImport } from './routes/api.guard'
import { Route as ApiPolicyRouteImport } from './routes/api.policy'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiAuditExportRouteImport } from './routes/api.audit.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionsRoute = ApiDecisionsRouteImport.update({
  id: '/api/decisions',
  path: '/api/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuardRoute = ApiGuardRouteImport.update({
  id: '/api/guard',
  path: '/api/guard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolicyRoute = ApiPolicyRouteImport.update({
  id: '/api/policy',
  path: '/api/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditExportRoute = ApiAuditExportRouteImport.update({
  id: '/api/audit/export',
  path: '/api/audit/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/guard': typeof ApiGuardRoute
  '/api/policy': typeof ApiPolicyRoute
  '/api/status': typeof ApiStatusRoute
  '/api/audit/export': typeof ApiAuditExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/guard': typeof ApiGuardRoute
  '/api/policy': typeof ApiPolicyRoute
  '/api/status': typeof ApiStatusRoute
  '/api/audit/export': typeof ApiAuditExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/guard': typeof ApiGuardRoute
  '/api/policy': typeof ApiPolicyRoute
  '/api/status': typeof ApiStatusRoute
  '/api/audit/export': typeof ApiAuditExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controls'
    | '/dashboard'
    | '/mcp'
    | '/playground'
    | '/api/decisions'
    | '/api/guard'
    | '/api/policy'
    | '/api/status'
    | '/api/audit/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/controls'
    | '/dashboard'
    | '/mcp'
    | '/playground'
    | '/api/decisions'
    | '/api/guard'
    | '/api/policy'
    | '/api/status'
    | '/api/audit/export'
  id:
    | '__root__'
    | '/'
    | '/controls'
    | '/dashboard'
    | '/mcp'
    | '/playground'
    | '/api/decisions'
    | '/api/guard'
    | '/api/policy'
    | '/api/status'
    | '/api/audit/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlsRoute: typeof ControlsRoute
  DashboardRoute: typeof DashboardRoute
  McpRoute: typeof McpRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ApiDecisionsRoute: typeof ApiDecisionsRoute
  ApiGuardRoute: typeof ApiGuardRoute
  ApiPolicyRoute: typeof ApiPolicyRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAuditExportRoute: typeof ApiAuditExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decisions': {
      id: '/api/decisions'
      path: '/api/decisions'
      fullPath: '/api/decisions'
      preLoaderRoute: typeof ApiDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guard': {
      id: '/api/guard'
      path: '/api/guard'
      fullPath: '/api/guard'
      preLoaderRoute: typeof ApiGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policy': {
      id: '/api/policy'
      path: '/api/policy'
      fullPath: '/api/policy'
      preLoaderRoute: typeof ApiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit/export': {
      id: '/api/audit/export'
      path: '/api/audit/export'
      fullPath: '/api/audit/export'
      preLoaderRoute: typeof ApiAuditExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlsRoute: ControlsRoute,
  DashboardRoute: DashboardRoute,
  McpRoute: McpRoute,
  PlaygroundRoute: PlaygroundRoute,
  ApiDecisionsRoute: ApiDecisionsRoute,
  ApiGuardRoute: ApiGuardRoute,
  ApiPolicyRoute: ApiPolicyRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiAuditExportRoute: ApiAuditExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
